name: format-check
on:
  push:
    branches:
      - 'master'
      - /^release-.*$/
    tags: '*'
  pull_request:
jobs:
  format-check:
    name: Format check (Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.5.3]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}

      - uses: actions/checkout@v1
      - name: Instantiate `format` environment and format
        # The version of JuliaFormatter used is just to show how to specify the version. The latest
        # version would be preferrable.
        run: |
          julia  --project=format -e 'using Pkg; Pkg.instantiate()'
          julia  --project=format 'format/run.jl'
      - name: Format check
        run: |
          julia -e '
          out = Cmd(`git diff --name-only`) |> read |> String
          if out == ""
              exit(0)
          else
              @error "Some files have not been formatted !!!"
              write(stdout, out)
              exit(1)
          end'
